name: Build and publish
on:
  push:
     branches:
       - '**'
     tags-ignore:
       - 'v**'
  release:
     types: [prereleased,released] 
env:
  IMAGE_PREFIX: ouestfrance/cdp-kubectl
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get image tag
        id: get_image_tag
        run:  |
          if [[ "${{github.event_name}}" == "release" ]]; then
             TAG=$IMAGE_PREFIX:${{ github.event.release.tag_name }}
          fi
          if [[ "${{github.event_name}}" != "release" ]]; then
             TAG=$IMAGE_PREFIX:${GITHUB_REF#refs/*/}-${{github.run_number}}
          fi
          if [[ "${{github.event_name}}" == "push" && "${{github.ref}}" == "refs/heads/master" ]]; then
             TAG=$TAG,$IMAGE_PREFIX:latest 
          fi
          echo ::set-output name=TAGS::$TAG       
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.get_image_tag.outputs.TAGS }}
